#pragma config(Sensor, in1,    rls,            sensorReflection)
#pragma config(Sensor, in2,    lls,            sensorReflection)
#pragma config(Sensor, dgtl1,  E0,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  E1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  E2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  E3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonar,          sensorSONAR_raw)
#pragma config(Motor,  port2,           Motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           Motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Motor4,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           bucket,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           nub,           tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX))
/*void ECUNI(){
SensorValue[E0] = SensorValue[E1] = SensorValue[E2] = SensorValue[E3] = 0;
if(Button == 1){

calibrate = false;
for(int i = 0; i < 10; i++){
wait1Msec(500);
if(Button == 0){
return;
}
if(i == 9){
calibrate = true;
}
}
}
if(calibrate == true){
SensorValue[E0] = 0;
SensorValue[E1] = 0;
SensorValue[E2] = 0;
SensorValue[E3] = 0;

motor[Motor1] = 127;
motor[Motor2] = 127;
motor[Motor3] = 127;
motor[Motor4] = 127;
wait1Msec(3000);
motor[Motor1] = 0;
motor[Motor2] = 0;
motor[Motor3] = 0;
motor[Motor4] = 0;
}
int min = 9999999999999999;
int cenc = NULL;
int sensorValues[] = {SensorValue[E0], SensorValue[E1], SensorValue[E2], SensorValue[E3]};

for(int i = 0; i < 4; i++){
if(sensorValues[i] < min){
min = sensorValues[i];
cenc = i;

}
}
}*/

task main()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		int LX = vexRT[Ch1];
		int LY = vexRT[Ch2];
		int Rotate = vexRT[Ch4] * -1;
		/*
		Motor1 -
		Motor2 -
		Motor3 -
		Motor4 -
		*/
		motor[Motor1] = LY + LX + Rotate;
		motor[Motor2] = -(LY) + LX + Rotate;
		motor[Motor3] = -(LY) + -(LX) + Rotate;
		motor[Motor4] = LY + -(LX) + Rotate;
		if(vexRT[Btn6U] == 1){
			motor[nub] = 500;
		}
		else if(vexRT[Btn5U] == 1){
			motor[nub] = -500;
		}
		else if(vexRT[Btn6D] == 1){
			motor[nub] = 60;
		}
		else if(vexRT[Btn5D] == 1){
			motor[nub] = -60;
		}
		else{
			motor[nub] = 0;
		}

		if(vexRT[Btn7U] == 1){
			motor[lclaw] = 40;
			motor[rclaw] = -40;
		}
		else if(vexRT[Btn7D] == 1){
			motor[lclaw] = -20;
			motor[rclaw] = 20;
		}
		else{
			motor[lclaw] = motor[rclaw] = 0;
		}
		if(vexRT[Btn8D] == 1){
			motor[bucket] = -70;
		}
		else if(vexRT[Btn8U] == 1){
			motor[bucket] = 90;
		}
		else{
			motor[bucket] = 0;
		}
	}
}
