#pragma config(Sensor, dgtl1,  E0,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  E1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  E2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  E3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonar,          sensorSONAR_raw)
#pragma config(Motor,  port2,           Motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           Motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Motor4,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

bool calibrate;
void ECUNI(){
	SensorValue[E0] = SensorValue[E1] = SensorValue[E2] = SensorValue[E3] = 0;
	if(Button == 1){

		calibrate = false;
		for(int i = 0; i < 10; i++){
			wait1Msec(500);
			if(Button == 0){
				return;
			}
			if(i == 9){
				calibrate = true;
			}
		}
	}
	if(calibrate == true){
		SensorValue[E0] = 0;
		SensorValue[E1] = 0;
		SensorValue[E2] = 0;
		SensorValue[E3] = 0;

		motor[Motor1] = 127;
		motor[Motor2] = 127;
		motor[Motor3] = 127;
		motor[Motor4] = 127;
		wait1Msec(3000);
		motor[Motor1] = 0;
		motor[Motor2] = 0;
		motor[Motor3] = 0;
		motor[Motor4] = 0;
	}
	int min = 9999999999999999;
	int cenc = NULL;
	int sensorValues[] = {SensorValue[E0], SensorValue[E1], SensorValue[E2], SensorValue[E3]};

	for(int i = 0; i < 4; i++){
		if(sensorValues[i] < min){
			min = sensorValues[i];
			cenc = i;

		}
	}
}

task drive()
{
	int LX = vexRT[Ch1];
	int LY = vexRT[Ch2];
	int Rotate = vexRT[Ch4];
	motor[Motor1] = LY + LX + Rotate;
	motor[Motor2] = -(LY) + LX + Rotate;
	motor[Motor3] = -(LY) + -(LX) + Rotate;
	motor[Motor4] = LY + -(LX) + Rotate;


}
