#pragma config(Sensor, in1,    rls,            sensorReflection)
#pragma config(Sensor, in2,    lls,            sensorReflection)
#pragma config(Sensor, dgtl1,  E0,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  E1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  E2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  E3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonar,          sensorSONAR_raw)
#pragma config(Motor,  port2,           Motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           Motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Motor4,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           nub,           tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

task main(){
	SensorValue[E0] = SensorValue[E1] = SensorValue[E2] = SensorValue[E3] = 0;
	wait1Msec(20);
	while(SensorValue[sonar] > 3){

		if(right > left){
			motor[Motor1] = 50;
			motor[Motor4] = 50;
			motor[Motor3] = 10;
			motor[Motor1] = 10;
		}
		if(right < left){
			motor[Motor1] = 10;
			motor[Motor4] = 10;
			motor[Motor3] = 50;
			motor[Motor1] = 50;
		}
		wait1Msec(2);
	}
	while(SensorValue[sonar] < 3){
			if(SensorValue[lls] > SensorValue[rls]){
				motor[nub] = 40;
			}
			if(SensorValue[lls] < SensorValue[rls]){
				motor[nub] = 40;
			}
			else{
				motor[nub] = 00;
			}
	}
}
