#pragma config(Sensor, in1,    ,               sensorReflection)
#pragma config(Sensor, dgtl1,  E0,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  E1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  E2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  E3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonar,          sensorSONAR_mm)
#pragma config(Motor,  port2,           Motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           Motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Motor4,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void CUNI(){
	int LX = vexRT[Ch1];
	int LY = vexRT[Ch2];
	int Rotate = vexRT[Ch4];
	motor[Motor1] = LY + LX + Rotate;
	motor[Motor2] = -(LY) + LX + Rotate;
	motor[Motor3] = -(LY) + -(LX) + Rotate;
	motor[Motor4] = LY + -(LX) + Rotate;
}

bool calibrate;
void ECUNI(){
	SensorValue[E0] = SensorValue[E1] = SensorValue[E2] = SensorValue[E3] = 0;
	if(Button == 1){

		calibrate = false;
		for(int i = 0; i < 10; i++){
			wait1Msec(500);
			if(Button == 0){
				return;
			}
			if(i == 9){
				calibrate = true;
			}
		}
	}
	if(calibrate == true){
		SensorValue[E0] = 0;
		SensorValue[E1] = 0;
		SensorValue[E2] = 0;
		SensorValue[E3] = 0;

		motor[Motor1] = 127;
		motor[Motor2] = 127;
		motor[Motor3] = 127;
		motor[Motor4] = 127;
		wait1Msec(3000);
		motor[Motor1] = 0;
		motor[Motor2] = 0;
		motor[Motor3] = 0;
		motor[Motor4] = 0;
	}
	int min = 9999999999999999;
	int cenc = NULL;
	int sensorValues[] = {SensorValue[E0], SensorValue[E1], SensorValue[E2], SensorValue[E3]};

	for(int i = 0; i < 4; i++){
		if(sensorValues[i] < min){
			min = sensorValues[i];
			cenc = i;

		}
	}
}





void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;


	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	SensorValue[E0] = SensorValue[E1] = SensorValue[E2] = SensorValue[E3] = 0;
	wait1Msec(20);
	while(SensorValue[sonar] > 3){
		int right = SensorValue[E0] + SensorValue[E3];
		int left = SensorValue[E1] + SensorValue[E2];
		if(right > left){
			motor[Motor1] = 50;
			motor[Motor4] = 50;
			motor[Motor3] = 10;
			motor[Motor1] = 10;
		}
		if(right < left){
			motor[Motor1] = 10;
			motor[Motor4] = 10;
			motor[Motor3] = 50;
			motor[Motor1] = 50;
		}
		wait1Msec(2);
	}
	while(SensorValue[sonar] < 3){
		if(
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
